### ISSUE TITLE
Checklist

### ISSUE THREAD

**Issue by BentTranberg** [BentTranberg/Holistic#2]
Things that needs doing...

The TodoDb.fs module EntTodo has four functions, of which only one has been unit tested (or even run) so far.

- [ ] EntTodo.getAll
- [x] EntTodo.get
- [ ] EntTodo.update
- [ ] EntTodo.insert

Other work that waits...

- [ ] Connection string should not be hardcoded. Where should it come from?
- [ ] Table Todo needs one or more additional fields, and corresponding logic must be added in EntTodo.
- [ ] The GUI needs a design.

When we discussed this demo - "a holistic demo" - in F# Slack, we landed on the "obligatory TODO list demo", and I thought perhaps https://github.com/Zaid-Ajaj/SAFE-TodoList might be something we could snatch pieces from. Having looked closer at it, I think it would be more work for me to try to adapt anything there. Instead, in the Elmish.WPF demos there's one nice demo where a panel with controls is used as an item in a tree list, and I think stealing some ideas from that will be perfect.
